language: ruby
rvm:
- 2.0.0-p353
- 2.1.0
- ruby-head
before_deploy:
- yard doc
deploy:
- provider: rubygems
  on:
    branch: master
  api_key:
    secure: Kkwrzg+2dJrrShwVceco8EEP8Kc9BsKvDWIK6pFrdalZRY4sDG7BC7phPOmQPW40Qvl9f3qaZFjpohN0/QLDlF48Zg2AUBGuKfWpQ7V+dTL7hd6ZewFEs/5vyoofEf7BkSE9NFrsuOymEtHH+MJjqY+aIFg4YrNRcoEvCFuEZRk=
