language: ruby
rvm:
- 2.0.0-p353
- 2.1.0
- ruby-head
notifications:
  flowdock:
    secure: LiGQvTUtEQyFRdM/nIDrzFI7aP5VGymCSGwrOFJ/ej//kiMc4fwjJqA+OD9JHT6bnBHx7BkFqXOMRIOBvxE2v5t0phmNJkEI9wc2Jiq6o9kdhMfVg9IQ8NTNdWK6cRqyfs96mLjFzweN+kUp6UnU/s9iXsU5XdOLYeklkC2U/sI=
before_deploy:
- yard doc
deploy:
- provider: s3
  access_key_id: AKIAIWPY43DAALLVSXFQ
  bucket: reuters.stockflare.com
  skip_cleanup: true
  local-dir: doc
  edge: true
  region: us-east-1
  endpoint: s3-us-east-1.amazonaws.com
  on:
    branch: master
  secret_access_key:
    secure: BS3KV3AbGIxzwmEA53iceavyM6MWuDImiAeIRN0CTiT3yCOsD8m5M8dzB1Uxx0nOQNj3W47ywpD2PDciEyr8RnEjMpLSPfEe1/bBJuiWUGDI5x2w2dg5M02/kJLMS3hFVbEvdoCN2owKpWA4Gm95JvkeWH8eL3JWIi7sxHC+Kxw=
- provider: rubygems
  on:
    branch: master
  api_key:
    secure: cDRvAU7Beo+0BNfgbAcyPvaTtR4yv539sm7Lkx0HOUMi+O9L/qhQgCCzacIwUeEAf5kPj9m7HSW5BzLddiOZlQ/rQLFOSctmzeF5Swj/oQZ6OqQDhvjjtazMrNiNvNvGmchbeEBdQw46q/aaAgHsvXWNtEjYES+4+3A8YVtCn+Q=
